project     = "quic-video"
region      = "us-central1"
zone        = "us-central1-f"
domain      = "quic.video"
email       = "kixelated@gmail.com"
image_pub   = "docker.io/kixelated/moq-rs"
image_relay = "docker.io/kixelated/moq-rs"
