#!/bin/bash
set -euo pipefail

# Function to find the first available command
find_command() {
    for cmd in "$@"; do
        if command -v "$cmd" &> /dev/null; then
            echo "$cmd"
            return
        fi
    done
    echo "Install one of: $@" >&2
    exit 1
}

# Find the first available command among podman and docker
# Originally, depot was on the list but it doesn't seem to play nicely with pushing via podman?
CMD=$(find_command podman docker)

# Build with arm/amd and push.
$CMD build --platform linux/arm64,linux/amd64 -t kixelated/moq-pub .
$CMD push kixelated/moq-pub
