#!/bin/sh

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Build moq-rs, assuming it's in the same directory as this repo
podman build ../moq-rs -t moq-rs

# gcloud auth configure-docker
# podman login us-central1-docker.pkg.dev

IMAGE=$(terraform output -raw relay_image)
podman push moq-rs "$IMAGE:latest"